version: '2'
services:
  testappliaction-app:
    image: testappliaction
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://testappliaction-postgresql:5432/TestAppliaction
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8088:8088
  testappliaction-postgresql:
    extends:
      file: postgresql.yml
      service: testappliaction-postgresql
