version: '2'
services:
  testappliaction-postgresql:
    image: postgres:11.5
    # volumes:
    #     - ~/volumes/jhipster/TestAppliaction/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=TestAppliaction
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
